# Generated by Django 6.1.1 on 2026-10-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
